[package]
name = "demostf-client"
version = "0.1.4"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"
description = "Api client for demos.tf"
license = "MIT OR Apache-2.0"
repository = "https://github.com/demostf/api-client"
readme = "README.md"
exclude = [ "tests/data/gully.dem" ]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.10", default-features = false, features = ["json"] }
thiserror = "1.0"
hex = "0.4"
steamid-ng = "0.3"

[dev-dependencies]
tokio = { version = "0.2", features = ["macros"] }
sqlx = { version = "0.4", features = ["postgres", "runtime-tokio-rustls"] }

[features]
default = ["default-tls"]
default-tls = ["reqwest/default-tls"]
rustls-tls = ["reqwest/rustls-tls"]