[package]
name = "demostf-client"
version = "0.3.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"
description = "Api client for demos.tf"
license = "MIT OR Apache-2.0"
repository = "https://github.com/demostf/api-client"
readme = "README.md"
exclude = [ "tests/data/gully.dem" ]

[dependencies]
serde = { version = "1", features = ["derive"] }
time = { version = "0.3", features = ["serde"] }
reqwest = { version = "0.11", default-features = false, features = ["json", "multipart", "stream"] }
thiserror = "1"
hex = "0.4"
steamid-ng = "1"
bytes = "1.1.0"
futures-util = "0.3.21"

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
sqlx = { version = "0.5", features = ["postgres", "runtime-tokio-rustls"] }

[features]
default = ["default-tls"]
default-tls = ["reqwest/default-tls"]
rustls-tls = ["reqwest/rustls-tls"]
